### ISSUE TITLE
Feature Request: Ability to filter out fields in an array of objects.

### ISSUE THREAD

**Issue by toinetoine** [mesqueeb/filter-anything#3]
Ability to filter out fields in an array of objects.

```javascript
    var ash = { 
        name: 'Ash Catch Em', 
        badges: [
            {name: 'Otoshi', year: 2001}
            {name: 'Mismagius', year: 2003}
            {name: 'Nando', year: 1999}
        ]
    }

    const filter = require('filter-anything');
    console.log(filter.omit(ash, ['badges.year']));
    /*
    name: 'Ash Catch Em', 
        badges: [
            {name: 'Otoshi'}
            {name: 'Mismagius'}
            {name: 'Nando'}
        ]
    }
    */
```
I guess syntax would have to be different, since omitting `'badges.year'` would remove `{badges: {year: ___}`  in addition to `{badges: [{year: ___}, ... ] }`. Maybe `['badges].year'` to specify that badges is an array of objects you want to omit the field `year` from? 
```

**Comment by mesqueeb** [comment]
Hi
thanks for your issue!

This is a use case that's too specific for me to support in my opinion.

If we agree on some syntax for this, it will always be a syntax that's not understandable from just looking at it, so I want to avoid this.

On the other hand, if you simply manually write what you want to achieve with the functions provided on arrays, it's easy to support this and when another developer looks at is there is no chance for any confusion.

Here is how you manually do this:
```js
const { omit } = require('filter-anything')

const ash = { 
	name: 'Ash Catch Em', 
	badges: [
		{name: 'Otoshi', year: 2001}
		{name: 'Mismagius', year: 2003}
		{name: 'Nando', year: 1999}
	]
}

const ashFilteredBadges = {
	...ash,
	badges: ash.badges.filter(badge => omit(badge, ['year']))
}
```
will equal to 
```js
{
	name: 'Ash Catch Em', 
	badges: [
		{name: 'Otoshi'}
		{name: 'Mismagius'}
		{name: 'Nando'}
	]
}
```

**Comment by toinetoine** [comment]
I wrote a similar function that loops over and resets each but your solution is much cleaner so I'll steal it if that's ok 😊

What you said makes sense, none of obvious syntax choices are understandable from just looking at it.
```javascript
    filter.omit(ash, '[badges].year');
    filter.omit(ash, 'badges[].year');
    filter.omit(ash, 'badges.[].year');
    filter.omit(ash, 'badges[i].year');
    filter.omit(ash, 'badges.[i].year');
```
